pull_request_rules:
  - name: Approve and merge Snyk.io upgrades
    conditions:
      - author=snyk-bot
      - check-success~=Lint
      - check-success~=Test
      - check-success~=Build Docker
      - title~=^\[Snyk\]
    actions:
      review:
        type: APPROVE
      merge:
        method: squash
